### ISSUE TITLE
Lock state doesn't update

### ISSUE THREAD

**Issue by mlachman** [ilcato/homebridge-fibaro-hc3#4]
Hello,

I have three danalock v3 zwave edition included in my zwave network operated by fibaro. In order to use them with homekit, I use the homebridge-fibaro-hc3 plugin. When I use homekit to open or close the lock, it works perfectly but the lock always seems open in the homekit app. It seems like the Lock State doesnt change.

The following message also appear in the log:

`[8/7/2020, 2:46:46 PM] [FibaroHC3] Setting value to device:  104  parameter: Lock Target State`
`[8/7/2020, 2:46:46 PM] [FibaroHC3] Command:  secure, value: 0, to: 104`
`[8/7/2020, 2:46:51 PM] [FibaroHC3] There was a problem setting value to Lock:  104`

**Comment by sossowski** [comment]
I have exactly the same problem with my danalock v3 zwave edition.

**Comment by ilcato** [comment]
Unfortunately this is very hard to analyze without a real device.

**Comment by dazcro** [comment]
Hi, I am experiencing a similar issue with Yale Lock with Zwave - It's like the lock is always unlocked in the Home App, but when i try to lock it, it sends the "Lock Command" to fibaro, but then the status remains as "unlocked" or "No Response"
I do have Charles Proxy, if there is something you would like me to test and provide debug info, please let me know.

**Comment by vkamenski** [comment]
+1

**Comment by khw1006** [comment]
getLockCurrentState function should be fixed like below

https://github.com/khw1006/homebridge-fibaro-hc3/commit/d53125caf14c1b2dfa6ec9c92f699945c8e9c245

**Comment by vkamenski** [comment]
> getLockCurrentState function should be fixed as follows
> 
> [khw1006@d53125c](https://github.com/khw1006/homebridge-fibaro-hc3/commit/d53125caf14c1b2dfa6ec9c92f699945c8e9c245)

Your fix works. I've verified it on my local installation with Danalock.  I think, it'd be logical to send a pull request with you fix as a next step.

**Comment by ilcato** [comment]
@khw1006 please pack a PR.
@vkamenski thanks for testing.

**Comment by ilcato** [comment]
@khw1006 @vkamenski just published version 1.0.9 containing the fix.

**Comment by vkamenski** [comment]
Hi,

Still getting the same error:
[28/03/2021, 13:52:13] [FibaroHC3] Setting value to device:  212  parameter: Lock Target State
[28/03/2021, 13:52:13] [FibaroHC3] Command:  secure, value: 0, to: 212
[28/03/2021, 13:52:13] [FibaroHC3] There was a problem setting value to Lock:  212

**Comment by dazcro** [comment]
This is now working for Yale Lock! Thanks

**Comment by vkamenski** [comment]
I have an issue with danalock v3 zwave

**Comment by ilcato** [comment]
@vkamenski try install the beta version homebridge-fibaro-hc3@beta

**Comment by vkamenski** [comment]
> @vkamenski try install the beta version homebridge-fibaro-hc3@beta

well, I'll better wait for the next release :)

**Comment by ilcato** [comment]
> I have an issue with danalock v3 zwave

What exactly is your issue?
